name: Deploy to GitHub Pages

on:
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22  # Use Node.js 22
        
    - name: Install pnpm
      run: npm install -g pnpm  # Install pnpm globally

    - name: Install dependencies
      run: pnpm install  # Use pnpm to install dependencies
        
    - name: Build
      run: pnpm run build  # Use pnpm to build the app
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./dist